version: "3"

services:
   ubuntu:
        image: ubuntu_gcc_clang
        container_name: ubuntu
        build: ./
        restart: on-failure
        environment:
            - DISPLAY=host.docker.internal:0
        volumes:
            - ubuntu_gcc_clang:/home/marvin/docker
            - /tmp/.X11-unix:/tmp/.X11-unix
        tty: true

volumes:
    ubuntu_gcc_clang:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${DLC_WORK_VOLUME_ORIGIN}
