version: "3"

services:
   ubuntu:
        image: ubuntu_gcc_clang
        container_name: ubuntu
        build: ./
        ports:
            - 3333:3333
        restart: on-failure
        environment:
            - DISPLAY=host.docker.internal:0
        volumes:
            - ubuntu_gcc_clang:${DLC_WORK_VOLUME_DESTINATION}
            - /tmp/.X11-unix:/tmp/.X11-unix
        working_dir: ${DLC_WORKING_DIR}
        tty: true

volumes:
    ubuntu_gcc_clang:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${DLC_WORK_VOLUME_ORIGIN}
